name: Deploy Releases

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-crates-io-release:
    name: Deploy to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: "wasm32-unknown-unknown"
    - run: cargo login ${{ env.CRATES_IO_TOKEN }}
      env:
        CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    - run: cargo publish --allow-dirty -p ag-grid-derive
    - run: sleep 20
    - run: cargo publish --allow-dirty -p ag-grid-rs

  create-gh-release:
    name: Deploy to GH Releases
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v1
